### ISSUE TITLE
Select default return format

### ISSUE THREAD

**Issue by atymic** [codegreencreative/laravel-freshworks#2]
Hey!

Thanks for the cool package :D

I'd like to be able to default returns to array. The docs mention being able to call `toArray` on the response, but the `go` method that does the response always calls `toObject`

**Comment by upwebdesign** [comment]
@atymic well, that is an interesting predicament. How could we update so it does not affect anyone using this package that is expecting an object?

**Comment by atymic** [comment]
We can leave the default as object, and add a config option to pick which return type.
If you set it to array, we call toArray instead of toObject.

We'd just need to remote the object type hints.

Ideally, I think actually returning an object with array access would be the best (then we can set response, etc)

**Comment by upwebdesign** [comment]
@atymic if you are interested in doing a PR for this that would be great! Let me know!

**Comment by atymic** [comment]
Hey @upwebdesign I had to jump onto a couple of other things but I will revisit soon :D

**Comment by atymic** [comment]
I PR'd exceptions and tests, will fork off that once merged.
